### ISSUE TITLE
Expose mysql

### ISSUE THREAD

**Issue by gponty** [jolicode/docker-starter#100]
Hi all,
First, thank you to share this docker-starter.
Is it possible to expose PG/mysql during development ? by example for use database tool, like Dbeaver ?
Or it's a bad practice ?
Thank you !

**Comment by lyrixx** [comment]
hello

Thanks for reaching us.

You have at least two options to do that:

* use the container ip and port in Dbeaver. You can get the IP thanks to the following command: 
  ```
  docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
  ```
  and the port is 5432
  
* add a port mapping in this [file](https://github.com/jolicode/docker-starter/blob/master/infrastructure/docker/docker-compose.yml#L28-L33)

  ```yaml
    postgres:
        build: services/postgres
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432" ### <-------- this line    
  ```
  Then use ip: 127.0.0.1 port:5432 in Dbeaver

---

Side note:I tried in the past to use traefik to route the TCP connection, but I failed because there are not "host resolution" at the TCP level. To do that we need TLS so I gave up after few tries

---

I'm gonna close your issue because I think I have answered your question. But if it's unclear, don't hesitate ta reply to this issue.
