### ISSUE TITLE
Find a workaround to have multiple projects running and talking on MacOS

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/docker-starter#127]
We want to use two Docker stater based project at the same time.

And project A needs to talk to project B.

It works well on Linux but as the network_mode "host" is not available on MacOS and Windows, we are stuck.

https://github.com/jolicode/docker-starter/blob/7ae34d5396e9c1fd1c8c102b8528c6aacd71a1c5/infrastructure/docker/docker-compose.docker-for-x.yml#L7-L8
https://github.com/docker/for-mac/issues/1031

_We added this on our frontend from project A:_

```
    frontend:
        build: services/frontend
        extra_hosts:
            - 'project-b.test:172.17.0.1' # Allow talking to project B, docker0 IP
```
