### ISSUE TITLE
Use M1 compatible base images?

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/docker-starter#203]
On some projects we have to add this to our Docker Compose files (`platform: linux/amd64`);

```
version: '3.7'

volumes:
    builder-data: {}

services:
    php-base:
        build: services/php-base
        platform: linux/amd64

    builder:
        build: services/builder
        platform: linux/amd64
```

To allow Macbooks with M1 chips to build.

It run but then it's painfully slow.

Could it be that our base images are not M1 compatible? Could we found images that runs anywhere?
